### ISSUE TITLE
New driver issue, easy fix.

### ISSUE THREAD

**Issue by jlaustill** [g0t4/aspnet-identity-mongo#12]
I downloaded your package today and got it to work, but boy did I struggle having never done a custom identity before :)  

There's a bugfix implemented in the mongo 2.1.1 drivers that stop your code from working, the fix is easy, just replaced [BsonRepresentation(BsonType.ObjectID)] with [BsonId] in both places it existed in the IdentityUser and IdentityRole, recompiled, and everything seems to be working for me.  

Here's the two lines

		[BsonId]
		public string Id { get; private set; }

Seems kind of silly to do a fork and pull request for something this simple, but I certainly will if you wish, just let me know.

Thanks for doing this, I'm using it over at www.joshuaaustill.com, which is my little sandbox.  I'll let you know if I run into anymore issues.

Have a great day!
Joshua Austill

**Comment by g0t4** [comment]
Will be updated in ASP.NET Core Identity provider
