### ISSUE TITLE
Your simple example does not work

### ISSUE THREAD

**Issue by gordon-matt** [g0t4/aspnet-identity-mongo#15]
There's an issue with your example code:

`var users = database.GetCollection<IdentityUser>("users");`
`var store = new UserStore<IdentityUser>(users);`

This causes the following compile-time error:

`"Argument 1: cannot convert from 'MongoDB.Driver.MongoCollection<IdentityUser>' to 'MongoDB.Driver.IMongoCollection<IdentityUser>'"`

This is the first time I have tried using this nuget package. Perhaps something changed and you are working with an older version of the mongo driver? My nuget packages are as follows:

`<package id="AspNet.Identity.MongoDB" version="2.0.8" targetFramework="net451" />`
`<package id="Microsoft.AspNet.Identity.Core" version="2.2.1" targetFramework="net451" />`
`<package id="Microsoft.AspNet.Identity.Owin" version="2.1.0" targetFramework="net451" />`
`<package id="mongocsharpdriver" version="2.2.3" targetFramework="net451" />`
`<package id="MongoDB.Bson" version="2.2.3" targetFramework="net451" />`
`<package id="MongoDB.Driver" version="2.2.3" targetFramework="net451" />`
`<package id="MongoDB.Driver.Core" version="2.2.3" targetFramework="net451" />`

**Comment by g0t4** [comment]
There will be a new example coming for Identity v3 with ASP.NET Core
