### ISSUE TITLE
Authorize(Roles="Admin") -attribute not working

### ISSUE THREAD

**Issue by yonzo** [g0t4/aspnet-identity-mongo#30]
When decorating my controller methods with i.e.:
_Autorize(Roles="Admin")_
I get the 404-errormessage "Not found".

If I remove _Roles="Admin"_, it's all good (as long as the user has logged in of course).
I might be missing some fundamental stuff here, but if so - please enlighten me!  :-)

Regards,
Yonzo

**Comment by g0t4** [comment]
This is likely the identity framework itself

**Comment by yonzo** [comment]
Ok, thanks - I'll look into it some more...

**Comment by nohwnd** [comment]
@yonzo This is caused by missing `Role` claim on the user. Identity framework uses claims for authorization by default now, so to achieve this your jwt token provider (or cookie provider) must add Role claim with value 'Admin' to the token.

**Comment by JonSomNor** [comment]
Thanks a lot nohwnd!
