### ISSUE TITLE
Timeout at MongoDb connection

### ISSUE THREAD

**Issue by eisenreich** [g0t4/aspnet-identity-mongo#32]
I tried to connect your sample [https://github.com/g0t4/aspnet-identity-mongo-sample/tree/master/AspNetCore.WebApp.MongoDB](url) with my MongoDb v3.4 Windows.
My ConnectionString is `mongodb://admin:abc123@localhost/TestDb` and with another ASP.NET Core app it works.
The log from MongoDb shows the following:
`2017-04-25T09:56:49.102+0200 I NETWORK  [thread1] connection accepted from 127.0.0.1:59254 #626 (7 connections now open)
2017-04-25T09:56:49.104+0200 I ACCESS   [conn626] SCRAM-SHA-1 authentication failed for someadmin on ErpDb from client 127.0.0.1:59254 ; UserNotFound: Could not find user someadmin@ErpDb
2017-04-25T09:56:49.106+0200 I -        [conn626] end connection 127.0.0.1:59254 (7 connections now open)`

**Comment by g0t4** [comment]
Did you resolve your issue?

**Comment by eisenreich** [comment]
Idk for sure. The problem was the authorization. I created via Robomongo a database and logged in with admin user. But with your version of logging in, the MongoClient was initialized differently.
Because of this I turned authorization off.

I'm also using MongoDb for persisting the "usual" application ressources.
Therefore I'm using the MongoDB.Driver too and I'm connection to the database with:
`var client = new MongoClient(settings.Value.ConnectionString);
 _database = client.GetDatabase(settings.Value.Database);`
In my _appsettings.json_ I got the following:
`  "MongoConnection": {  
    "ConnectionString": "mongodb://admin:abc123@localhost",  
    "Database": "ErpDb"
  },`
With this way of initializing everything works fine and if the database doesn't exist it will be created.

EDIT: It would be nice if it's possible to give a kind of context class into your _AddIdentityWithMongoStoresUsingCustomTypes_. Or register it over a function.
Please correct, if I'm in wrong context with it.
