### ISSUE TITLE
please upgrade this library to .Net core 2.0?

### ISSUE THREAD

**Issue by svpatel401** [g0t4/aspnet-identity-mongo#35]
I have tried to upgrade this class library to .Net core 2.0, without any issue.

In sample application, we have extension method - AddIdentityWithMongoStore.  I was not able to find any reference to this on github code shared by you.   Where is file MongoIdentityBuilderExtensions?

```
 // Register identity framework services and also Mongo storage. 
	        services.AddIdentityWithMongoStores(Configuration.GetConnectionString("DefaultConnection"))
		        .AddDefaultTokenProviders();
```

Appreciate if you can upgrade the library along with sharing code for MongoIdentityBuilderExtensions.

Thank you.

**Comment by vladimir-kucher** [comment]
Same thing here. Need this project under .net core 2.0. Please update!

**Comment by codepoc** [comment]
@g0t4 - Hope you are doing great.  I am running into same issue.  Appreciate your insight.  Thanks a lot.

**Comment by kenyeung128** [comment]
same here thanks @g0t4

**Comment by nrhoffmann** [comment]
same here @g0t4

**Comment by nohwnd** [comment]
@svpatel401 The code [is there](https://github.com/g0t4/aspnet-identity-mongo/blob/netcore/src/Microsoft.AspNetCore.Identity.MongoDB/MongoIdentityBuilderExtensions.cs#L73), it is just not on the master branch. I am successfully using this library build from sources with .NET Core 2.0 app, but it would be nice to have it available on nuget.

**Comment by svpatel401** [comment]
@nohwnd  - Thank you much.  Can someone give this man a trophy - he deserves it.

**Comment by g0t4** [comment]
I'll have a chance to look at this Thursday. I'm swamped until then. 

Did the APIs change? 

If not this should be compatible with netcoreapp2.0 by adding a package reference.

**Comment by svpatel401** [comment]
@g0t4  Missing piece of info according to me is "MongoIdentityBuilderExtensions", which then be pointed by @nohwnd 

Few suggestions to make this lib even better:
1. Change the namespace, so that it doesn't look like it is coming from Microsoft.  (It was much confusing in the beginning)
2. Add ApplicationUser class to the library, so that test web application doesn't have any change, except deleting existing ApplicationUser class.  (This are giving some wired errors because by default we are using IdentityUser in library).  Solution:  would be either change things in test web application or library.  I would prefer changing in library to keep things as simple as possible.

```
An unhandled exception occurred while processing the request.

InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.UserManager`1[TestMvcWebApp.Models.ApplicationUser]' has been registered.
Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
```

**Comment by razzeee** [comment]
I also think the namespace change would be a good thing.
