### ISSUE TITLE
Store does not implement IQueryableUserStore<TUser>

### ISSUE THREAD

**Issue by XmichaelcX** [g0t4/aspnet-identity-mongo#9]
Hi There,

Thanks for the project. Great help.

I was unable to use it at first due to the error (also with IQueryableRoleStore<TRole>):
Store does not implement IQueryableUserStore<TUser>

I was able to extend the Stores to implement the missing features. This was kinda hacked together since I havent been able to look at the new MongoDB driver.
public virtual System.Linq.IQueryable<TUser> Users
        {
            get
            {
                return _Users.Find(new BsonDocumentFilterDefinition<TUser>(new BsonDocument())).ToListAsync().Result.AsQueryable();
            }
        }
Could you suggest what Ive done wrong with your original implementation?

Hope this helps!
Michael

**Comment by g0t4** [comment]
Can you send me a stack trace to look at of the original exception?

**Comment by XmichaelcX** [comment]
Source Error: 

Line 59:             var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(ApplicationIdentityContext.Create().Users));
Line 60:             
Line 61:             var users = UserManager.Users.ToList();
Line 62:             return View(users);
Line 63:         }

Source File: d:\Code\Working\Projects\HOS\HOS Website\Controllers\UserAdminController.cs    Line: 61 



[NotSupportedException: Store does not implement IQueryableUserStore<TUser>.]
   Microsoft.AspNet.Identity.UserManager`2.get_Users() +117
   HOS_Website.Controllers.<Index>d__0.MoveNext() in d:\Code\Working\Projects\HOS\HOS Website\Controllers\UserAdminController.cs:61
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +93
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +52
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +84
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) +17
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +50
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +225
   System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +26
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +39
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +28
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +29
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +36
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +54
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +31
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9651116
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

**Comment by g0t4** [comment]
I patched up these issues by updating the example to go directly to MongoDB for querying all users/roles and even in one case show how we can write a succinctly query to find users in a role, a benefit of going directly to MongoDB's driver to query this in one pass instead of an n+1 lookup.

**Comment by g0t4** [comment]
And just for fun, here's my rationale for what I did https://www.youtube.com/watch?v=8t6KORVKqBg&feature=youtu.be

**Comment by XmichaelcX** [comment]
Hi Wes,

Thanks for your work on this - your proposition makes a lot of sense. It seems like a poor choice to expose the Users property via the UserManager interface and potentially why people are reporting poor performance when breaking away from EF implementations. 

Great video ;)

**Comment by g0t4** [comment]
My pleasure,

Yeah I never was a huge fan on the monstrosity of the UserManager
abstraction. I also find it rather entertaining how convoluted the EF
implementation is versus MongoDB, in all honesty if you use MongoDB I don't
feel the abstractions do that much for you in terms of managing the User
and Role models. The components to integrate with security and otherwise
are valuable and that's why I went ahead with the provider, otherwise it
would be an exercise in what not to do :)
